// <auto-generated />
namespace Kutse_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddHolidayIdToGuest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHolidayIdToGuest));
        
        string IMigrationMetadata.Id
        {
            get { return "202501230024173_AddHolidayIdToGuest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
